import datetime

order_dict = {
    "correct": [
        {
            "symbol": "TUNCAY",
            "source": "Questrade",
            "state": "Active",
            "filledQuantity": 55,
            "side": "Buy",
            "avg_exec_price": 555,
            "exec_time": datetime.datetime(2017, 2, 14, 15, 45),
            "strategyType": "Single Leg",
            "portfolio_id": 1,
            "fee": 5666,
            "position_id": 2,
            "order_id": 1,
        },
        {
            "symbol": "TUNCAY",
            "source": "Questrade",
            "state": "Active",
            "filledQuantity": 55,
            "side": "Buy",
            "avg_exec_price": 555,
            "exec_time": datetime.datetime(2017, 2, 14, 15, 45),
            "strategyType": "Single Leg",
            "portfolio_id": 1,
            "fee": 5666,
            "position_id": 2,
            "order_id": None,
        },
    ],
    "wrong": [
        {
            "symbol": "TUNCAY",
            "source": "Questrade",
            "state": "Active",
            "filledQuantity": 55,
            "side": "Buy",
            "avg_exec_price": 555,
            "exec_time": "World",
            "strategyType": "Hello",
            "portfolio_id": 1,
            "fee": 5666,
            "position_id": 2,
            "order_id": None,
        },
        {
            "symbol": "TUNCAY",
            "source": "Questrade",
            "state": "Active",
            "filledQuantity": 55,
            "side": "Buy",
            "avg_exec_price": 555,
            "exec_time": datetime.datetime(2017, 2, 14, 15, 45),
            "strategyType": "Single Leg",
            "portfolio_id": 1,
            "fee": None,
            "position_id": 2,
            "order_id": None,
        },
    ],
}