version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hello_flask_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db