version: "3.8"
   
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - main

  app:
    build: .
    environment:
      FLASK_CONFIG: development
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    container_name: app
    hostname: app
    depends_on:
      - redis
    expose:
      - "5001"
    ports:
      - "5001:5001"
    image: app-image
    restart: on-failure
    networks:
      - main

  worker:
    image: app-image
    environment:
      FLASK_CONFIG: development
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    command: celery -A celery_worker.celery worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis
      - app
    hostname: celery_worker
    restart: on-failure
    networks:
      - main

  celery_beat:
    image: app-image
    environment:
      FLASK_CONFIG: development
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    command: celery -A celery_worker.celery beat --loglevel=info
    container_name: celery_beat
    depends_on:
      - redis
      - app
    hostname: celery_beat
    restart: on-failure
    networks:
      - main

networks:
  main: