FROM python:3.9.4-slim
LABEL maintainer="tuncutku10@gmail.com"

ARG SECRET_KEY=1234
ARG SECURITY_PASSWORD_SALT=1234
ARG MAIL_SERVER_PASSWORD=1234

ENV FLASK_APP=run_app.py
ENV FLASK_CONFIG=docker
ENV SECRET_KEY=${SECRET_KEY}
ENV SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
ENV MAIL_SERVER_EMAIL=portfolioengineerofficial@gmail.com
ENV MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}

COPY . 	/app
WORKDIR /app

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3"]
CMD ["run_app.py"]
