version: "3.8"
   
services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - main

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - main

  app:
    build: .
    environment:
      FLASK_CONFIG: docker
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    container_name: app
    hostname: app
    depends_on:
      - redis
      - postgres
    expose:
      - "5001"
    ports:
      - "5001:5001"
    image: app-image
    restart: on-failure
    networks:
      - main
  
  worker:
    image: app-image
    environment:
      FLASK_CONFIG: docker
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    command: celery -A celery_worker.celery worker --loglevel=info
    container_name: celery_worker
    depends_on:
      - redis
      - postgres
      - app
    hostname: celery_worker
    restart: on-failure
    networks:
      - main

  celery_beat:
    image: app-image
    environment:
      FLASK_CONFIG: docker
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
      MAIL_SERVER_EMAIL: ${MAIL_SERVER_EMAIL}
      MAIL_SERVER_PASSWORD: ${MAIL_SERVER_PASSWORD}
    command: celery -A celery_worker.celery beat --loglevel=info
    container_name: celery_beat
    depends_on:
      - redis
      - postgres
      - app
    hostname: celery_beat
    restart: on-failure
    networks:
      - main

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    container_name: pgadmin4
    depends_on:
      - postgres
    hostname: pgadmin4
    restart: on-failure
    ports:
      - "5050:80"
    networks:
      - main

networks:
  main:

volumes:
  postgres: