version: 2.1

############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master

##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: circleci/python:3.9.4
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run:
          name: Install dependents and test
          command: |
            python3 -m venv env/
            . env/bin/activate
            pip install -r requirements/docker.txt
            export FLASK_APP=run.py
            flask test 


            
  # deploy:
  #   executor: heroku/default
  #   steps:
  #     - checkout
  #     - add_ssh_keys:
  #         fingerprints:
  #           - '48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4'
  #     - heroku/install
  #     - heroku/deploy-via-git:
  #         force: true