name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . -t tuncutku/portfolio_engineer:latest
    - name: Push the image to Docker
      run: docker push tuncutku/portfolio_engineer:latest

  test:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MAIL_SERVER_EMAIL: ${{ secrets.MAIL_SERVER_EMAIL }}
      MAIL_SERVER_PASSWORD: ${{ secrets.MAIL_SERVER_PASSWORD }}
      SECURITY_PASSWORD_SALT: ${{ secrets.SECURITY_PASSWORD_SALT }}
    container:
      image: tuncutku/portfolio_engineer:latest
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Test with pytest
      run: pytest -n auto
    # - name: Push the image to Heroku and deploy
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #   run: |
    #     heroku container:login
    #     heroku container:push -a portfolioengineer web