name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
    - name: Install dependencies
      run: |
        ./doit.sh
    - name: Run tests
      run: |
        ./doit.sh run_tests
