name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      MAIL_SERVER_EMAIL: ${{ secrets.MAIL_SERVER_EMAIL }}
      MAIL_SERVER_PASSWORD: ${{ secrets.MAIL_SERVER_PASSWORD }}
      SECURITY_PASSWORD_SALT: ${{ secrets.SECURITY_PASSWORD_SALT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; 
    - name: Run tests
      run: |
        pytest --cov=src --cov-config=tests/.coveragerc --no-cov-on-fail -n auto
    - name: Run pylint
      run: |
        pylint src/
        pylint tests/
